spring.application.name=biblioteca-inteligente

spring.datasource.url=jdbc:postgresql://localhost:5432/DbBibliotecaInteligente
spring.datasource.username=postgres
spring.datasource.password=TU_CONTRASEÑA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
